FROM openproject/openproject:16.4.1

ENV RAILS_ENV=production
ENV OPENPROJECT_DEFAULT__LANGUAGE=en 
ENV OPENPROJECT_HOST__NAME=openproject.traincloud.dev
ENV OPENPROJECT_MAIL__FROM=mail@traincloud.dev
ENV OPENPROJECT_CACHE_STORE=file_store
ENV PORT=10003

EXPOSE 10003
