apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: internal-apps-openproject-storage-logs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ionos-enterprise-ssd  # IONOS storage class