apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: default
  labels:
    app: gitea
spec:
  type: NodePort
  selector:
    app: gitea
  ports:
    - protocol: TCP
      targetPort: 10003  # Container-Port
      port: 20003       # Cluster-intern
      nodePort: 30003   # NodePort (30000–32767)