apiVersion: v1
kind: Service
metadata:
  name: openproject-service
  namespace: default
  labels:
    app: openproject
spec:
  type: NodePort
  selector:
    app: openproject
  ports:
    - protocol: TCP
      targetPort: 10005  # Container-Port
      port: 20005       # Cluster-intern
      nodePort: 30005   # NodePort (30000–32767)