apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-openproject-assets
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ionos-enterprise-ssd  # IONOS storage class