apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-storage-assets
  namespace: internal-apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ionos-enterprise-ssd  # IONOS storage class