apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-storage-config
  namespace: internal-apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ionos-enterprise-ssd  # IONOS storage class