apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-storage-logs
  namespace: internal-apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ionos-enterprise-ssd  # IONOS storage class